# Generated by Django 5.1.6 on 2025-03-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_name', models.CharField(max_length=50, null=True)),
                ('achievement_description', models.CharField(max_length=255, null=True)),
                ('achievement_id', models.CharField(max_length=30, null=True)),
                ('points_awarded', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
            },
        ),
    ]
