# Generated by Django 5.1.6 on 2025-03-24 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_achievement_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='achievement_type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='achievement_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
