# Generated by Django 5.1.6 on 2025-03-21 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('badges', '0002_badge_points_awarded_alter_badge_image'),
        ('challenges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('player', 'Player'), ('game_keeper', 'Game Keeper'), ('developer', 'Developer')], default='player', max_length=20)),
                ('points', models.IntegerField(default=0)),
                ('registration_bonus_claimed', models.BooleanField(default=False)),
                ('daily_bonus_time_claimed', models.DateTimeField(blank=True, null=True)),
                ('badges', models.ManyToManyField(blank=True, to='badges.badge')),
                ('challenges_completed', models.ManyToManyField(blank=True, to='challenges.challenge')),
                ('quizzes_completed', models.ManyToManyField(blank=True, to='challenges.quiz')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
