# Generated by Django 5.1.6 on 2025-03-23 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_achievements'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='achievements',
            new_name='achievements_completed',
        ),
    ]
