# Generated by Django 5.1.6 on 2025-02-20 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_daily_bonus_time_remaining'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='daily_bonus_time_remaining',
            new_name='daily_bonus_time_claimed',
        ),
    ]
