# Generated by Django 5.1.6 on 2025-03-23 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_achievements_userprofile_achievements_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='achievements_completed',
            new_name='completed_achievements',
        ),
    ]
