# Generated by Django 5.1.6 on 2025-02-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_daily_bonus_time_remaining_userprofile_daily_bonus_time_claimed'),
        ('challenges', '0009_remove_quiz_completed_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='quizzes_completed',
            field=models.ManyToManyField(blank=True, to='challenges.quiz'),
        ),
    ]
