# Generated by Django 5.1.6 on 2025-02-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_quizzes_completed'),
        ('challenges', '0011_merge_20250224_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='challenges_completed',
            field=models.ManyToManyField(blank=True, to='challenges.challenge'),
        ),
    ]
