# Generated by Django 5.1.6 on 2025-03-21 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_name', models.CharField(max_length=50, null=True)),
                ('bonus_description', models.CharField(max_length=255, null=True)),
                ('bonus_id', models.CharField(max_length=30, null=True)),
                ('points_awarded', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Bonus',
                'verbose_name_plural': 'Bonuses',
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_name', models.CharField(max_length=50, null=True)),
                ('challenge_description', models.CharField(max_length=255, null=True)),
                ('challenge_id', models.CharField(max_length=30, null=True)),
                ('points_awarded', models.IntegerField(default=0)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Challenge',
                'verbose_name_plural': 'Challenges',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_name', models.CharField(max_length=50, null=True)),
                ('quiz_description', models.CharField(max_length=255, null=True)),
                ('quiz_id', models.CharField(max_length=50, null=True)),
                ('quiz_question', models.CharField(max_length=255, null=True)),
                ('quiz_option_one', models.CharField(max_length=255, null=True)),
                ('quiz_option_two', models.CharField(max_length=255, null=True)),
                ('quiz_option_three', models.CharField(max_length=255, null=True)),
                ('quiz_option_four', models.CharField(max_length=255, null=True)),
                ('quiz_answer', models.CharField(max_length=255, null=True)),
                ('points_awarded', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='submissions/')),
                ('approved', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
