# Generated by Django 5.1.6 on 2025-03-24 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='submitted_at',
        ),
    ]
