# Generated by Django 5.1.6 on 2025-02-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_challenge_challenge_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='challenge_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
