# Generated by Django 5.1.6 on 2025-02-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_challenge_challenge_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_name', models.CharField(max_length=50, null=True)),
                ('quiz_question', models.CharField(max_length=255, null=True)),
                ('quiz_answer', models.CharField(max_length=255, null=True)),
                ('points_awarded', models.IntegerField(default=0)),
            ],
        ),
    ]
