# Generated by Django 5.1.6 on 2025-02-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_alter_challenge_options_alter_quiz_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='challenge_description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
