# Generated by Django 5.1.6 on 2025-02-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0006_challenge_challenge_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_option_four',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_option_one',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_option_three',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_option_two',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
