# Generated by Django 5.1.6 on 2025-02-21 14:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0007_quiz_quiz_option_four_quiz_quiz_option_one_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='completed_users',
            field=models.ManyToManyField(blank=True, related_name='completed_quizzes', to=settings.AUTH_USER_MODEL),
        ),
    ]
