# Generated by Django 5.1.6 on 2025-02-22 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0008_quiz_completed_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='completed_users',
        ),
    ]
