# Generated by Django 5.1.6 on 2025-02-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0009_remove_quiz_completed_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='challenge',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
