# Generated by Django 5.1.6 on 2025-02-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0009_remove_quiz_completed_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_name', models.CharField(max_length=50, null=True)),
                ('bonus_description', models.CharField(max_length=255, null=True)),
                ('bonus_id', models.CharField(max_length=30, null=True)),
                ('points_awarded', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Bonus',
                'verbose_name_plural': 'Bonuses',
            },
        ),
    ]
