# Generated by Django 5.1.6 on 2025-02-24 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0010_bonus'),
        ('challenges', '0010_challenge_latitude_challenge_longitude'),
    ]

    operations = [
    ]
