# Generated by Django 5.1.7 on 2025-03-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0002_badge_points_awarded_alter_badge_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='purchasable',
            field=models.BooleanField(default=False),
        ),
    ]
