# Generated by Django 5.1.7 on 2025-03-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0003_badge_purchasable'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
