# Generated by Django 5.1.6 on 2025-03-24 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0004_badge_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='points_awarded',
        ),
    ]
